#!/usr/bin/env bash
# Customizing a 404-error_page

#g Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
#echo "Holberton School" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
#new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Clint07-datascientist permanent;"
#sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
#echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
#new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

#sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Creating an HTTP response header
#sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
#sudo nginx -t

# Restart nginx after implementing changes
#sudo service nginx restart

echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
REDIRECT_301="\\\trewrite ^/redirect_me https://google.com permanent;"
sudo sed -i "41i $REDIRECT_301" /etc/nginx/sites-available/default
REDIRECT_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $REDIRECT_404" /etc/nginx/sites-available/default
ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default
sudo service nginx start
