#!/usr/bin/env bash
#commands to install- nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Holberton School" | sudo tee /var/www/html/index.html

#test nginx configs
sudo nginx -t

sudo service nginx restart
